import Modal from "../components/Modal";
import Button from "../components/Button";
import { useState } from 'react';

function ModalPage(){
  const [showModal, setShowModal] = useState(false);

  const handleClick = () =>{
    setShowModal(true);
  }

  const handleClose = () =>{
    setShowModal(false);
  }

  const actionBar = <div>
    <Button onClick={handleClose} success>I Accept</Button>
  </div>

  const modal = <Modal  onClose={handleClose} actionBar={actionBar} >
    <p className="">
      Do you agree to our Terms & Conditions?
    </p>
  </Modal>

  return(
    <div className="relative">
      <Button onClick={handleClick} primary>Open Modal</Button>
      { showModal && modal }
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut ad ullam dicta neque quisquam accusamus quos nobis quaerat reiciendis hic, error iste rerum commodi doloremque optio voluptates tempora sed non consequatur eligendi odio. Vel expedita voluptate error corrupti earum neque eum impedit, recusandae ex, eveniet nulla amet debitis repellendus. Reiciendis unde, nam qui laborum, necessitatibus iure eius nulla vel distinctio, neque natus odit assumenda totam? Facilis tenetur corporis possimus doloremque laudantium unde consectetur error distinctio explicabo optio perferendis minima, nisi aspernatur recusandae odio cupiditate, voluptas impedit reprehenderit voluptate? Rerum fugiat eum consectetur esse cupiditate ex veritatis in! Deserunt nesciunt repellat odio ad, obcaecati totam numquam labore aliquam reprehenderit. Aliquid repellendus perferendis expedita alias, veniam tenetur eaque iure et! Laborum maxime, perferendis consequatur neque praesentium, quaerat ab iusto atque obcaecati in facere? Blanditiis et tenetur sit saepe quos eligendi ipsum, possimus at laboriosam quas illo, eaque aliquid repellendus hic impedit officiis voluptatum exercitationem reprehenderit repudiandae ipsam optio suscipit! Alias accusamus ipsa, natus temporibus, assumenda maxime nesciunt aliquid doloremque, impedit odio culpa quibusdam recusandae beatae inventore harum aut ab voluptate porro! Dolor fuga pariatur ipsam accusamus, animi, possimus enim sunt modi, quas alias aut. Voluptas, debitis! Doloribus recusandae facere repellat suscipit.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut ad ullam dicta neque quisquam accusamus quos nobis quaerat reiciendis hic, error iste rerum commodi doloremque optio voluptates tempora sed non consequatur eligendi odio. Vel expedita voluptate error corrupti earum neque eum impedit, recusandae ex, eveniet nulla amet debitis repellendus. Reiciendis unde, nam qui laborum, necessitatibus iure eius nulla vel distinctio, neque natus odit assumenda totam? Facilis tenetur corporis possimus doloremque laudantium unde consectetur error distinctio explicabo optio perferendis minima, nisi aspernatur recusandae odio cupiditate, voluptas impedit reprehenderit voluptate? Rerum fugiat eum consectetur esse cupiditate ex veritatis in! Deserunt nesciunt repellat odio ad, obcaecati totam numquam labore aliquam reprehenderit. Aliquid repellendus perferendis expedita alias, veniam tenetur eaque iure et! Laborum maxime, perferendis consequatur neque praesentium, quaerat ab iusto atque obcaecati in facere? Blanditiis et tenetur sit saepe quos eligendi ipsum, possimus at laboriosam quas illo, eaque aliquid repellendus hic impedit officiis voluptatum exercitationem reprehenderit repudiandae ipsam optio suscipit! Alias accusamus ipsa, natus temporibus, assumenda maxime nesciunt aliquid doloremque, impedit odio culpa quibusdam recusandae beatae inventore harum aut ab voluptate porro! Dolor fuga pariatur ipsam accusamus, animi, possimus enim sunt modi, quas alias aut. Voluptas, debitis! Doloribus recusandae facere repellat suscipit.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut ad ullam dicta neque quisquam accusamus quos nobis quaerat reiciendis hic, error iste rerum commodi doloremque optio voluptates tempora sed non consequatur eligendi odio. Vel expedita voluptate error corrupti earum neque eum impedit, recusandae ex, eveniet nulla amet debitis repellendus. Reiciendis unde, nam qui laborum, necessitatibus iure eius nulla vel distinctio, neque natus odit assumenda totam? Facilis tenetur corporis possimus doloremque laudantium unde consectetur error distinctio explicabo optio perferendis minima, nisi aspernatur recusandae odio cupiditate, voluptas impedit reprehenderit voluptate? Rerum fugiat eum consectetur esse cupiditate ex veritatis in! Deserunt nesciunt repellat odio ad, obcaecati totam numquam labore aliquam reprehenderit. Aliquid repellendus perferendis expedita alias, veniam tenetur eaque iure et! Laborum maxime, perferendis consequatur neque praesentium, quaerat ab iusto atque obcaecati in facere? Blanditiis et tenetur sit saepe quos eligendi ipsum, possimus at laboriosam quas illo, eaque aliquid repellendus hic impedit officiis voluptatum exercitationem reprehenderit repudiandae ipsam optio suscipit! Alias accusamus ipsa, natus temporibus, assumenda maxime nesciunt aliquid doloremque, impedit odio culpa quibusdam recusandae beatae inventore harum aut ab voluptate porro! Dolor fuga pariatur ipsam accusamus, animi, possimus enim sunt modi, quas alias aut. Voluptas, debitis! Doloribus recusandae facere repellat suscipit.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut ad ullam dicta neque quisquam accusamus quos nobis quaerat reiciendis hic, error iste rerum commodi doloremque optio voluptates tempora sed non consequatur eligendi odio. Vel expedita voluptate error corrupti earum neque eum impedit, recusandae ex, eveniet nulla amet debitis repellendus. Reiciendis unde, nam qui laborum, necessitatibus iure eius nulla vel distinctio, neque natus odit assumenda totam? Facilis tenetur corporis possimus doloremque laudantium unde consectetur error distinctio explicabo optio perferendis minima, nisi aspernatur recusandae odio cupiditate, voluptas impedit reprehenderit voluptate? Rerum fugiat eum consectetur esse cupiditate ex veritatis in! Deserunt nesciunt repellat odio ad, obcaecati totam numquam labore aliquam reprehenderit. Aliquid repellendus perferendis expedita alias, veniam tenetur eaque iure et! Laborum maxime, perferendis consequatur neque praesentium, quaerat ab iusto atque obcaecati in facere? Blanditiis et tenetur sit saepe quos eligendi ipsum, possimus at laboriosam quas illo, eaque aliquid repellendus hic impedit officiis voluptatum exercitationem reprehenderit repudiandae ipsam optio suscipit! Alias accusamus ipsa, natus temporibus, assumenda maxime nesciunt aliquid doloremque, impedit odio culpa quibusdam recusandae beatae inventore harum aut ab voluptate porro! Dolor fuga pariatur ipsam accusamus, animi, possimus enim sunt modi, quas alias aut. Voluptas, debitis! Doloribus recusandae facere repellat suscipit.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut ad ullam dicta neque quisquam accusamus quos nobis quaerat reiciendis hic, error iste rerum commodi doloremque optio voluptates tempora sed non consequatur eligendi odio. Vel expedita voluptate error corrupti earum neque eum impedit, recusandae ex, eveniet nulla amet debitis repellendus. Reiciendis unde, nam qui laborum, necessitatibus iure eius nulla vel distinctio, neque natus odit assumenda totam? Facilis tenetur corporis possimus doloremque laudantium unde consectetur error distinctio explicabo optio perferendis minima, nisi aspernatur recusandae odio cupiditate, voluptas impedit reprehenderit voluptate? Rerum fugiat eum consectetur esse cupiditate ex veritatis in! Deserunt nesciunt repellat odio ad, obcaecati totam numquam labore aliquam reprehenderit. Aliquid repellendus perferendis expedita alias, veniam tenetur eaque iure et! Laborum maxime, perferendis consequatur neque praesentium, quaerat ab iusto atque obcaecati in facere? Blanditiis et tenetur sit saepe quos eligendi ipsum, possimus at laboriosam quas illo, eaque aliquid repellendus hic impedit officiis voluptatum exercitationem reprehenderit repudiandae ipsam optio suscipit! Alias accusamus ipsa, natus temporibus, assumenda maxime nesciunt aliquid doloremque, impedit odio culpa quibusdam recusandae beatae inventore harum aut ab voluptate porro! Dolor fuga pariatur ipsam accusamus, animi, possimus enim sunt modi, quas alias aut. Voluptas, debitis! Doloribus recusandae facere repellat suscipit.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut ad ullam dicta neque quisquam accusamus quos nobis quaerat reiciendis hic, error iste rerum commodi doloremque optio voluptates tempora sed non consequatur eligendi odio. Vel expedita voluptate error corrupti earum neque eum impedit, recusandae ex, eveniet nulla amet debitis repellendus. Reiciendis unde, nam qui laborum, necessitatibus iure eius nulla vel distinctio, neque natus odit assumenda totam? Facilis tenetur corporis possimus doloremque laudantium unde consectetur error distinctio explicabo optio perferendis minima, nisi aspernatur recusandae odio cupiditate, voluptas impedit reprehenderit voluptate? Rerum fugiat eum consectetur esse cupiditate ex veritatis in! Deserunt nesciunt repellat odio ad, obcaecati totam numquam labore aliquam reprehenderit. Aliquid repellendus perferendis expedita alias, veniam tenetur eaque iure et! Laborum maxime, perferendis consequatur neque praesentium, quaerat ab iusto atque obcaecati in facere? Blanditiis et tenetur sit saepe quos eligendi ipsum, possimus at laboriosam quas illo, eaque aliquid repellendus hic impedit officiis voluptatum exercitationem reprehenderit repudiandae ipsam optio suscipit! Alias accusamus ipsa, natus temporibus, assumenda maxime nesciunt aliquid doloremque, impedit odio culpa quibusdam recusandae beatae inventore harum aut ab voluptate porro! Dolor fuga pariatur ipsam accusamus, animi, possimus enim sunt modi, quas alias aut. Voluptas, debitis! Doloribus recusandae facere repellat suscipit.</p>
    </div>
  );
}

export default ModalPage;