# Get All Book
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###
# Create a new book
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
  "title": "Harry Potter"
}

### 
# Edit a book
PUT http://localhost:3001/books/4682 HTTP/1.1
Content-Type: application/json

{
  "title": "Harry Topper"
}

### 
# Delete a book
DELETE http://localhost:3001/books/4682 HTTP/1.1
Content-Type: application/json
